### ISSUE TITLE
Add TVMaze parsers

### ISSUE THREAD

**Issue by labrys** [mediares/mediares#2]
Add parsers for data from TVMaze API 
See mediares/mediares#1

- [ ] Add Schedule parser
- [x] Add Network parser (see PR mediares/mediares#4)
- [X] Add Web Channel parser (see PR mediares/mediares#7)
- [ ] Add Series parser
- [X] Add Season parser (see PR mediares/mediares#22)
- [X] Add Episode parser (see PR mediares/mediares#16)
- [x] Add Person parser (see PR mediares/mediares#13)
- [ ] Add Cast parser
- [X] Add Character parser (see mediares/mediares#14)
- [ ] Add Crew parser
- [X] Add Update parser (see mediares/mediares#23)
